version: '3'
services:
   
  autismweb:
    environment: 
      - "URL=http://134.209.202.175:8000"
      - "NODE_ENV=production"
    command: >
      npm start
    ports: 
      - "3000:3000"
      
  dautism:
    ports: 
      - "8000:8000"
