# Generated by Django 2.2.3 on 2019-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_auto_20190722_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('posts', models.ManyToManyField(related_name='exams', to='posts.Post')),
            ],
        ),
    ]
