# Generated by Django 2.2.3 on 2019-07-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answer_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.Experiment'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
            preserve_default=False,
        ),
    ]
