# Generated by Django 2.2.3 on 2019-08-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190729_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='has_autism',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='has_background',
            field=models.BooleanField(default=False),
        ),
    ]
