# Generated by Django 2.2.3 on 2019-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(upload_to='images/')),
                ('seconod_image', models.ImageField(upload_to='images/')),
                ('sound_one', models.FileField(upload_to='sounds/')),
                ('sound_two', models.FileField(upload_to='sounds/')),
            ],
        ),
    ]
