# Generated by Django 2.2.3 on 2019-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_autism',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='has_background',
            field=models.BooleanField(default=False),
        ),
    ]
