# Generated by Django 2.2.3 on 2019-08-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190826_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='has_autism',
        ),
        migrations.RemoveField(
            model_name='post',
            name='has_background',
        ),
    ]
